### ISSUE TITLE
Directory structure changes

### ISSUE THREAD

**Issue by Lignumm** [Lignumm/Radium#1]
Wouldn't it be wiser to have startup in root so that you can just clone the repo into your computer directory?

**Comment by Lignumm** [comment]
Actually, I just symlinked src as my computer folder... it's still a bit quirky and won't work on Windows though.

**Comment by apemanzilla** [comment]
I have it symlinked on Windows to ccemuredux just fine, `mklink /D 0 <path>` was what I used.

I was planning on keeping the source code in a separate folder so documents like the README don't get downloaded with the OS.
