### ISSUE TITLE
Filesystem structure

### ISSUE THREAD

**Issue by Lignumm** [Lignumm/Radium#13]
Before I get started with the filesystem, I think it'd be good if we agreed on a structure first. I made a little chart to demonstrate my idea:
![](https://dl.dropboxusercontent.com/u/87257025/filesystem.svg)

Essentially, any FS call that is made will be redirected into some sort of path registry, which will find out which file server owns that path. That file server is then responsible for handling the FS call.

**Comment by apemanzilla** [comment]
That makes sense. I would do it with routes similar to how Express works - you can register custom handlers for various directories which all follow a basic structure.

**Comment by Lignumm** [comment]
Heh, I actually had Express in mind too when I made that chart. But yes, that's how the path manager will work, I suppose. It will map certain directories to a file server. By the way, shall I call them file providers or something else to avoid them being confused with file servers like FTP/Samba?

**Comment by apemanzilla** [comment]
File providers should be fine IMO. They provide files. Not much else to it.
