### ISSUE TITLE
Duplicate entries in programs program

### ISSUE THREAD

**Issue by Lignumm** [Lignumm/Radium#18]
Some entries (such as `besh.lua`) are duplicated in the `programs` program. The relevant code is in `besh.lua`'s `shell.programs()` function.

**Comment by apemanzilla** [comment]
Also, directories show up - and are resolved as programs.

**Comment by Lignumm** [comment]
Huh, I thought I fixed that. I'll check it out tomorrow.

**Comment by apemanzilla** [comment]
Also some entries show up with `nil` appended to the end? ![Image](https://i.imgur.com/2UdXBcT.png)

**Comment by Lignumm** [comment]
Solved as of 87e0854ad7abf94758d65d68d30f90dc94b0b665. Fixing the duplicates also fixed the nil ones for some reason.
