### ISSUE TITLE
CraftOS backwards compatibility

### ISSUE THREAD

**Issue by apemanzilla** [Lignumm/Radium#25]
Given how extensive the modules have become, I wanted to ask if you thought this would still be a viable feature - a program to compile programs to run on standard CraftOS.

At this point, we'd pretty much have to ship the entire OS in with the program unless we stripped down the system modules quite a bit, and I'm not sure how we would handle the filesystem wrapper.

Should we even bother with this? Or should we just focus on CraftOS to Radium compatibility?

**Comment by Lignumm** [comment]
Hm yeah, CraftOS -> Radium compat should be the only thing to worry about. If people want to run Radium programs, they should install Radium.

**Comment by apemanzilla** [comment]
Alright, fair enough.
