### ISSUE TITLE
Should libraries be structured "CraftOS style" or "Lua style"

### ISSUE THREAD

**Issue by apemanzilla** [Lignumm/Radium#3]
Should libraries create globals and be run in special environments to load them, like CraftOS? Or should we do it like Lua does it, where libraries return tables?

Personally I'm leaning towards Lua style, and maybe provide a fallback on CraftOS style if nothing is returned.

**Comment by Lignumm** [comment]
I'm all for Lua style.

**Comment by apemanzilla** [comment]
Alright, I'll do that then.
