### ISSUE TITLE
PATH troubles

### ISSUE THREAD

**Issue by Lignumm** [Lignumm/Radium#4]
If you switch to the `besh` branch, you may notice that some programs, like `pastebin` fail to run. This happens because these programs are in subdirectories in `/rom/programs`. In case of pastebin, this is `/rom/programs/http` iirc.

This is a problem and our only options are pretty much:
- Put all subdirectories into the PATH. This is how CraftOS does it.
- Modify system.paths.resolve to search recursively. (=> Optional parameter?)

**Comment by apemanzilla** [comment]
I'm actually not sure which way would be best. Probably CraftOS style to prevent people running turtle programs on a computer.

**Comment by Lignumm** [comment]
Good point, I'll just copy the CraftOS path over for now.
