### ISSUE TITLE
Fatal error when besh is killed via shell.exit

### ISSUE THREAD

**Issue by apemanzilla** [Lignumm/Radium#6]
I figured out the concurrent modification exception. shell.exit, which kills besh, is called during the main loop in procmgr.distribute - this will cause an error. Instead of setting processes to nil, maybe we can instead flag them with 'killed' or similar, and then remove them all after the distribute loop completes.

**Comment by Lignumm** [comment]
Fixed in 4d8f2696292e953ab361b96ad19d9f686fc8f85e.
