### ISSUE TITLE
Implement a hierarchical process tree system

### ISSUE THREAD

**Issue by apemanzilla** [Lignumm/Radium#9]
If a parent process is killed, its children should be killed too, for example.

**Comment by Lignumm** [comment]
How do we go about doing that? Shall each process contain its parents and children or shall the process table assume a tree-like structure?

**Comment by apemanzilla** [comment]
I feel like a tree structure would be best in the long run, albeit requiring more changes. Just adding parent/child PID tracking would be slow to iterate the arrays each time.

**Comment by apemanzilla** [comment]
I can work on this once I get home in an hour or so. I'm also going to fix a few other bugs that I've found, so I'll branch off of besh and make a PR when I'm done.

**Comment by Lignumm** [comment]
Alright, could you also update the chart? The Unix-style core is pretty much finished, no? And Besh should be in progress. I guess I'll get started on the filesystem...

**Comment by apemanzilla** [comment]
I'll update the chart after I implement some fixes and we merge to master.

**Comment by apemanzilla** [comment]
Coming back to this issue, I can't think of an efficient way to implement this with actual tree structured tables. What are your thoughts on instead having `parent` and `child` fields containing PIDs?

**Comment by Lignumm** [comment]
Sure. Maybe the fields could be metatables whose __index points to the real process table?

**Comment by apemanzilla** [comment]
Yeah, that sounds good. I'll work on this in a bit.

**Comment by apemanzilla** [comment]
Actually, why use metatables at all? Tables are soft-copied in Lua, so simply setting the process's `parent` field to the table of its parent should work fine.

**Comment by Lignumm** [comment]
Oh yeah, good point. Let's do that then.

**Comment by apemanzilla** [comment]
Finally, how do you want to implement it? I have a few ideas:

- Use `getfenv(2).__PID__` to get the PID of the process calling `procmgr.new` - this is the easiest to implement, but won't work when/if CC moves to Lua 5.2
- Create a different `procmgr.new` method that also takes a parent's PID - this would allow processes to be 'attached' to other processes, and give them more control (which could be good or bad)
- Add a process creation function to the environment of processes that will create a process from the parent's PID

**Comment by apemanzilla** [comment]
Done as of bacab99
